### ISSUE TITLE
Components Plan

### ISSUE THREAD

**Issue by yiminghe** [react-component/react-component.github.io#1]
## Docs
- [x] [docs](https://github.com/react-component/react-component.github.io/blob/master/docs) @yiminghe
- [x] [badgeboard](http://react-component.github.io/badgeboard/) @yiminghe  
- [x] [site](http://react-component.github.io)  @yiminghe
- [x] [ant-design](http://ant.design/) @afc163 
## Infrastructure
- [x] [generator-rc](https://github.com/react-component/generator-rc) @yiminghe  
### ant-design
- [x] [calendar(日期选择控件)](https://github.com/react-component/calendar) @yiminghe 
- [x] [dialog/modal/confirm](https://github.com/react-component/dialog) @yiminghe  
- [x] [table(简单表格)](https://github.com/react-component/table)  @yiminghe 
- [x] [tabs(选项卡)](https://github.com/react-component/tabs) @yiminghe  
- [x] [pager(分页)](https://github.com/react-component/pager)  
- [x] [pagination(分页)](https://github.com/react-component/pagination)  
- [x] [menu(菜单)](https://github.com/react-component/menu) @warmhug
- [x] [select(下拉菜单)](https://github.com/react-component/select) @warmhug/@yiminghe 
- [x] [form-validator(表单验证)](https://github.com/react-component/form-validation) @yiminghe 
- [x] [radio(单选框)](https://github.com/react-component/radio) @yiminghe
- [x] [checkbox(多选框)](https://github.com/react-component/checkbox) @yiminghe
- [x] [tree](https://github.com/react-component/tree) @warmhug
- [x] [slider(滑动选择器)](https://github.com/react-component/slider) @simaQ 
- [x] [input-number(数字输入框)](https://github.com/react-component/input-number) @yiminghe
- [x] [progress(进度条)](https://github.com/react-component/progress) @夏奈 
- [x] [switch(开关)](https://github.com/react-component/switch) @yiminghe
- [x] [step(步鄹)](https://github.com/react-component/steps)
- [x] [tooltip(通用提示)](https://github.com/react-component/tooltip) @yiminghe 
- [x] [dropdown(气泡弹出层)](https://github.com/react-component/dropdown) @yiminghe 
- [x] [dropzone(拖放上传)](https://github.com/react-component/dropzone) @shepherdwind 
- [x] [upload(通用上传)](https://github.com/react-component/upload) @shepherdwind
- [x] [notification(信息提示条)](https://github.com/react-component/notification) @yiminghe
- [x] [collapse(折叠面板)](https://github.com/react-component/collapse)  @翰文
- [x] [color-picker(颜色选择)](https://github.com/react-component/react-colors-picker)
### other (低优先级)
- [ ] Bar Chart  ? [prototype](http://yiminghe.me/learning-react/example/react-art/index-build.html)
- [ ] Pie Chart ? 
- [ ] Line Chart ?
## Refer
- [组件规范](https://github.com/react-component/react-component.github.io)
- https://github.com/yiminghe/learning-react
- [火烧云组件库](http://site.alipay.im/flaming-cloud-components)
- [ant-design](http://demo.alibaba-inc.com/categories/1977/projects/13137)
- http://react-components.com

**Comment by hustxiaoc** [comment]
tree @hustxiaoc

**Comment by sskyy** [comment]
tooltip  
progress bar

**Comment by tsj1107** [comment]
number input

**Comment by sliuqin** [comment]
switch button

**Comment by yiminghe** [comment]
add  bar chart prototype http://yiminghe.me/learning-react/example/react-art/index-build.html

**Comment by tsj1107** [comment]
page-progress 
progress-circle
pager

**Comment by afc163** [comment]
@yiminghe 承玉
@shepherdwind 翰文
@sliuqin 蔡伦
@warmhug 然则
