### ISSUE TITLE
remove redundancy  object-assign

### ISSUE THREAD

**Issue by paranoidjk** [react-component/react-component.github.io#15]
https://github.com/search?q=org%3Areact-component+object-assign&type=Code

since  `rc-tools` and `antd-tools`  both use `babel-plugin-transform-object-assign`, no need to use a third-party module.

cc @react-component/admin 

- [x] rc-canlendar

**Comment by benjycui** [comment]
这个依赖不好去掉，使用率太高了，包括 `create-react-class` 都用了，看到可以顺手去掉，不去影响也不大。

**Comment by paranoidjk** [comment]
恩，我也是这个意思，目前看到的都顺手去了，但也没必要开个 issue 在这里 TODO 了。
