### ISSUE TITLE
Tooltip Design

### ISSUE THREAD

**Issue by yiminghe** [react-component/react-component.github.io#3]
@sliuqin for refer
## functionality
- http://spmjs.io/package/arale-tip
## api
- http://react-bootstrap.github.io/components.html#tooltips
## align util
- http://spmjs.io/docs/dom-align/latest/examples/
## api

```
<Tip event='onmouse'  content={<a>xss</a>}>
<a>xxx</a>
</Tip>
```

**Comment by shepherdwind** [comment]
I think that kind api just not so friendly.  Mostly, Tip should not wrap the trigger elemet.

I recommend api like below code:

```
<Tip target={el} triggerType='hover'>hello, show this</Tip>
```

**Comment by yiminghe** [comment]
用法是这样的

```
一段话，中间想要单词<Tip content={<a>translate</a>}>翻译</Tip>，完了
```

**Comment by shepherdwind** [comment]
嗯，这样也行，我本来想到的tip，可能是可以动的，从一个元素到另外一个元素，不过这样的需求比较少。

**Comment by yiminghe** [comment]
https://github.com/react-component/tooltip

done
