### ISSUE TITLE
topics

### ISSUE THREAD

**Issue by yiminghe** [react-component/react-component.github.io#6]
## 2015-05-14

[react-best-practice](https://speakerdeck.com/yiminghe/react-best-practice)
## 2015-06-01

[roof-preview](https://speakerdeck.com/sskyy/roof-preview)
## 2015-06-18

[ant-design-preview](https://speakerdeck.com/yiminghe/ant-design-preview)

react at alipay

react at alibaba data department
## 2015-07-30

[react-europe 2015](http://yiminghe.me/learning-react/tutorial/zh-cn/meetings/react-europe-2015.html)
## 2015-09-18

[relay-falcor-roof](https://speakerdeck.com/yiminghe/relay-falcor-roof)
## 2015-11-12

jest

**Comment by ishenli** [comment]
感谢分享~~
