### ISSUE TITLE
fix components lint

### ISSUE THREAD

**Issue by yiminghe** [react-component/react-component.github.io#8]
## lint 修复

删除 node_modules，重新 npm install，运行 npm run lint, warning 可以通过在文件头部加入：

``` js
/* eslint react/no-multi-comp:0 */
```
## 待修复组件列表
- [x] tabs: @yiminghe
- [x] input-number/progress/slider/switch: @本杰
- [ ] time-picker: @崖鹰
- [x] queue-anim/table/form-validation/notification: @偏右
- [x] pagination: @雨维
- [x] tree: @然则

**Comment by afc163** [comment]
`eslint --fix` 可以自动修复少数错误。
