### ISSUE TITLE
为什么不用ES6 class, 必须用React.createClass?

### ISSUE THREAD

**Issue by kingzs70** [react-component/react-component.github.io#9]
ES6 是未来，mixin只是一个特殊时期的临时解决方案，mixin有很多设计上的问题。为什么在代码规范中强调，必须用React.createClass呢？

[https://github.com/react-component/react-component.github.io/blob/master/docs/zh-cn/code-style/js.md#代码格式](https://github.com/react-component/react-component.github.io/blob/master/docs/zh-cn/code-style/js.md#代码格式)

**Comment by yiminghe** [comment]
binding this 很烦

**Comment by xujihui1985** [comment]
es6的 bind  `::` 语法可以不用bind this

**Comment by benjycui** [comment]
See: http://babeljs.io/blog/2015/05/14/function-bind/
